### ISSUE TITLE
Comments/Documentation

### ISSUE THREAD

**Issue by fernviridian** [AltOS-Rust/altos-rust#56]
This issue is for tracking code that needs additional attention to the documented and comments. In general this is because:

- Purpose of code is unclear
- Purpose of specific lines is obfuscated, not clear of purpose
- "Generally needs comments" means not only comments outside the function, but inline comments as well.
- Code from outside sources not properly accredited
- Dead code that should be removed from the project (Commented out code)
<br>

- [x] [altos-core/src/lib.rs] (https://github.com/AltOS-Rust/altos-rust/blob/88ac544289138c6c5e9d1223792df2352d2a2e63/altos-rust/src/lib.rs)
  - [x] This file should contain strong documentation on how to set up tasks to run on the system
<br>

- [x] [altos-rust/port/cortex-m0/src/lib.rs](https://github.com/AltOS-Rust/altos-rust/blob/88ac544289138c6c5e9d1223792df2352d2a2e63/altos-rust/port/cortex-m0/src/lib.rs)
  - [ ] Remove Dead Code (ln 25, ln 37)
<br>

- [x] [altos-rust/port/cortex-m0/src/peripheral/gpio/moder.rs](https://github.com/AltOS-Rust/altos-rust/blob/88ac544289138c6c5e9d1223792df2352d2a2e63/altos-rust/port/cortex-m0/src/peripheral/gpio/moder.rs)
  - [x] Line 98 unclear code needs comment
<br>

- [x] [altos-rust/port/cortex-m0/src/peripheral/gpio/ospeedr.rs](https://github.com/AltOS-Rust/altos-rust/blob/88ac544289138c6c5e9d1223792df2352d2a2e63/altos-rust/port/cortex-m0/src/peripheral/gpio/ospeedr.rs)
  - [x] Line 90 unclear code needs comment
<br>

- [x] [altos-core/port/coretex-m0/src/peripheral/gpio/otyper.rs](https://github.com/AltOS-Rust/altos-rust/blob/88ac544289138c6c5e9d1223792df2352d2a2e63/altos-rust/port/cortex-m0/src/peripheral/gpio/otyper.rs)
  - [x] Line 74/74 unclear code needs comment
  - [x] Line 88 unclear code needs comment
<br>

- [x] [altos-core/port/coretex-m0/src/peripheral/gpio/pupdr.rs](https://github.com/AltOS-Rust/altos-rust/blob/88ac544289138c6c5e9d1223792df2352d2a2e63/altos-rust/port/cortex-m0/src/peripheral/gpio/pupdr.rs)
  - [x] Line 90 unclear code needs comment
<br>

- [x] [altos-core/port/coretex-m0/src/peripheral/systick/current_value.rs](https://github.com/AltOS-Rust/altos-rust/blob/88ac544289138c6c5e9d1223792df2352d2a2e63/altos-rust/port/cortex-m0/src/peripheral/systick/current_value.rs)
  - [x] Line 41 comment on why this value is used as the mask is needed 
<br>

- [x] [altos-rust/port/cortex-m0/src/peripheral/systick/reload_value.rs](https://github.com/AltOS-Rust/altos-rust/blob/88ac544289138c6c5e9d1223792df2352d2a2e63/altos-rust/port/cortex-m0/src/peripheral/systick/reload_value.rs)
  - [x] Line 44 comment on why this value is used as the mask is needed 
<br>

- [x] [altos-core/src/queue/queue.rs](https://github.com/AltOS-Rust/altos-rust/blob/fa3467905b060a2ea9537b726b2acd1d9648524b/altos-rust/altos-core/src/queue/queue.rs)
  - [x] Comments needed for each block of code
<br>

- [x] [altos-core/src/queue/sorted_list.rs](https://github.com/AltOS-Rust/altos-rust/blob/fa3467905b060a2ea9537b726b2acd1d9648524b/altos-rust/altos-core/src/queue/sorted_list.rs)
  - [x] Iterator methods could use comments
  - [x] reference in `***self.head.as_ref().unwrap()` not apparently clear. Maybe explain?
  - [x] Remove dead code (modify_all function)
<br>

- [x] [altos-core/src/syscall/mod.rs](https://github.com/AltOS-Rust/altos-rust/blob/fa3467905b060a2ea9537b726b2acd1d9648524b/altos-rust/altos-core/src/syscall/mod.rs)
  - [x] L230 - could use some comments explaining if block logic
  - [x] L300 - FOREVER_CHAN "special logic" never explained. What is this special logic?
  - [x] L492 - test task, remove dead code here
<br>

- [x] [altos-core/src/task/args.rs](https://github.com/AltOS-Rust/altos-rust/blob/fa3467905b060a2ea9537b726b2acd1d9648524b/altos-rust/altos-core/src/task/args.rs)
  - [x] L249 - unclear `fn new` purpose. Looks to reverse args, but is not explained why it is called new.
<br>

- [x] [altos-core/src/task/control.rs](https://github.com/AltOS-Rust/altos-rust/blob/fa3467905b060a2ea9537b726b2acd1d9648524b/altos-rust/altos-core/src/task/control.rs)
  - [x] In general, file could use explanatory comments
<br>

- [x] [altos-rust/port/cortex-m0/libs/arm/src/asm.rs](https://github.com/AltOS-Rust/altos-rust/blob/fa3467905b060a2ea9537b726b2acd1d9648524b/altos-rust/port/cortex-m0/libs/arm/src/asm.rs)
  - [x] In general, file could use explanatory comments
<br>

- [x] [altos-rust/port/cortex-m0/libs/arm/src/lib.rs](https://github.com/AltOS-Rust/altos-rust/blob/fa3467905b060a2ea9537b726b2acd1d9648524b/altos-rust/port/cortex-m0/libs/arm/src/lib.rs)
  - [x] Is this file only used for exposing internal ASM modules? Is it even needed? Some comments about the file purpose would be great.
<br>

- [x] [altos-rust/port/cortex-m0/libs/arm/src/math.rs](https://github.com/AltOS-Rust/altos-rust/blob/fa3467905b060a2ea9537b726b2acd1d9648524b/altos-rust/port/cortex-m0/libs/arm/src/math.rs)
  - [x] Could use some comments about file purpose.
  - [x] comments on C bindings, how you found the proper functions, etc
  - [x] comments explaining each function as this is not clear.
<br>

- [x] [altos-rust/port/cortex-m0/libs/arm/src/mem.rs](https://github.com/AltOS-Rust/altos-rust/blob/fa3467905b060a2ea9537b726b2acd1d9648524b/altos-rust/port/cortex-m0/libs/arm/src/mem.rs)
  - [x] Could use some comments about file purpose.
  - [x] comments on C bindings, how you found the proper functions, etc
  - [x] explain what memset is doing in the while loop?
  - [x] source that was cited in math.rs is not cited here. I suspect it should be. 
  - [x] Remove dead code
<br>

- [x] [altos-core/src/task/stack.rs](https://github.com/AltOS-Rust/altos-rust/blob/fa3467905b060a2ea9537b726b2acd1d9648524b/altos-rust/altos-core/src/task/stack.rs)
  - [x] Remove dead code

**Comment by RJ-Russell** [comment]
I don't understand why the Queue needs more comments? The doc comments provided seem to be more than descriptive for what the code is expected to do.
