### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by fernviridian** [AltOS-Rust/altos-rust#61]
Deleted

**Comment by RJ-Russell** [comment]
Tests should not have comments as they should have self-describing names. Adding comments as to what the test does is incredibly redundant.

**Comment by L0ntra** [comment]
Ben, Mohammed and I talked about this and our suggestion is that all the test need comments describing the steps that are being taken to perform the test. Simply having a good name isn't always enough. An example of the type of comment we are looking for is:
```
/// Name of Test
/// STEPS
/// - Add a Normal and a Low Priority task to the scheduling queue
/// - Start the Scheduler and perform a context switch 10 times checking the priority of the current 
///   task each time
/// FAIL IF:
/// - The Low task is scheduled before the 10th Context Switch
/// - The Normal task is scheduled after the 10th Context Switch
```
Doesn't necessarily need to be doc comments, but this is the general idea.

**Comment by RJ-Russell** [comment]
On some level, I still disagree with this. I don't think this needs to pertain to all tests.  Having comments on some of the more complex tests might be a good idea (on a case by case basis), but not necessarily in the form provided. I feel like the place for that is in a test document, not in the test code.

**Comment by L0ntra** [comment]
What is simple and clear enough to you, may not be to others. Having this basic level of information (even on simple tests) will help future developers both when they are adding new tests to the system or if the tests starts failing, and the cause needs to be investigated.
