### ISSUE TITLE
Trying to print hexadecimal fails

### ISSUE THREAD

**Issue by dnseitz** [AltOS-Rust/altos-rust#77]
When trying to print a number in hexadecimal, i.e.
```rust
kprintln!("{:X}", 100);
```
nothing is printed and the system locks up.

Could be an issue with the formatting code or the printing itself. Hopefully it's not some compiler intrinsic function that's failing this time...

**Comment by RJ-Russell** [comment]
Moved to: https://github.com/AltOS-Rust/cm0-port/issues/7
